### ISSUE TITLE
Improve test coverage on ts-sdk, output test coverage to MRs and SonarQube

### ISSUE THREAD

**Issue by cgilbe27** [NibiruChain/ts-sdk#234]

**Comment by Unique-Divine** [comment]
We can add more tx tests since `ts-sdk` runs against an actual network:

https://github.com/NibiruChain/ts-sdk/blob/releases/v0.21.x/packages/nibijs/src/tx/signingClient.test.ts

Currently, it looks like we only run through certain perp transactions and simple transfers. We could make the suite more robust by including wasm transactions and other messages

**Comment by cgilbe27** [comment]
Closing as completed with 90%+ coverage overall
